name: macOS

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"  
jobs:

  ci:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: isolette-module
      - name: Cache ScalaJS Standalone
        id: cache-scalajs
        uses: actions/cache@v2
        with:
          path: isolette-module/hamr/slang/lib
          key: ${{ runner.os }}-1.7.1-scalajs
      - name: Test
        run: |
          export COURSIER_CACHE=$GITHUB_WORKSPACE/cache/coursier

          cd $GITHUB_WORKSPACE

          git clone --rec https://github.com/sireum/kekinian.git

          export SIREUM_HOME=${PWD}/kekinian

          cd $SIREUM_HOME/hamr/codegen/arsit
          git checkout module
          git pull --recurse
          
          $SIREUM_HOME/bin/build.cmd setup
          
          export PATH=$SIREUM_HOME/bin:$PATH

          $SIREUM_HOME/bin/install/fmide.cmd

          $GITHUB_WORKSPACE/isolette-module/aadl/bin/clean.cmd
          
          $GITHUB_WORKSPACE/isolette-module/aadl/bin/run-hamr-linux.cmd

          $GITHUB_WORKSPACE/isolette-module/aadl/bin/stacksize-fix.cmd

          $GITHUB_WORKSPACE/isolette-module/hamr/slang/bin/scalajs.cmd

          $GITHUB_WORKSPACE/isolette-module/hamr/c/bin/compile.cmd
          
      - name: 'Upload JS'
        uses: actions/upload-artifact@v3
        with:
          name: generated-mac-site
          path: |
            isolette-module/hamr/slang/index.html
            isolette-module/hamr/slang/js/main.js
          retention-days: 5
