name: Windows

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"  
jobs:

  ci:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: isolette-module
      - name: Install Cygwin
        shell: cmd
        run: |
          choco config get cacheLocation
          choco install --no-progress cygwin
          C:\tools\cygwin\cygwinsetup.exe -qgnNdO -R C:/tools/cygwin -s http://mirrors.kernel.org/sourceware/cygwin/ -P gcc-core,gcc-g++,make,cmake          
      - name: Cache ScalaJS Standalone
        id: cache-scalajs
        uses: actions/cache@v2
        with:
          path: isolette-module\hamr\slang\lib
          key: ${{ runner.os }}-1.7.1-scalajs
      - name: Check LongPathsEnabled
        run: |
          (Get-ItemProperty "HKLM:System\CurrentControlSet\Control\FileSystem").LongPathsEnabled          
      - name: Test
        shell: cmd
        run: |
          xcopy %GITHUB_WORKSPACE%\cache\coursier %HOMEDRIVE%%HOMEPATH%\cache\coursier\ /E/H
          set COURSIER_CACHE=%HOMEDRIVE%%HOMEPATH%\cache\coursier

          set PATH=C:\tools\cygwin\bin;C:\tools\cygwin\usr\bin;%PATH%
          set CC=gcc.exe
          set CXX=c++.exe

          cd /d %GITHUB_WORKSPACE%

          git clone --rec https://github.com/sireum/kekinian.git

          set SIREUM_HOME=%GITHUB_WORKSPACE%\kekinian

          cd %SIREUM_HOME%\hamr\codegen\arsit
          git checkout module
          git pull --recurse

          call %SIREUM_HOME%\bin\build.cmd setup

          echo Done installing kekinian.  Errorlevel %errorlevel%

          if %errorlevel% neq 0 (
            if exist %SIREUM_HOME%\out\sireum-proyek\assemble\sireum.jar (

              REM build.cmd sometimes fails on windows when it tries to
              REM replace the in-use bin\sireum.jar with the freshly built one.
              REM Workaround is to manually copy the jar over

              copy %SIREUM_HOME%\out\sireum-proyek\assemble\sireum.jar %SIREUM_HOME%\bin\

              echo Manually copied sireum.jar to bin. Errorlevel %errorlevel%
            ) else (
              echo "Error occurred while building sireum.jar"
              exit %errorlevel%
            )
          )
          
          set PATH=%SIREUM_HOME%\bin;%PATH%

          call %SIREUM_HOME%\bin\install\fmide.cmd fixed
          echo Done installing FMIDE. Errorlevel %errorlevel%
          
          if %errorlevel% neq 0 exit /b %errorlevel%
          
          
          call %GITHUB_WORKSPACE%\isolette-module\aadl\bin\clean.cmd
            
          call %GITHUB_WORKSPACE%\isolette-module\aadl\bin\run-hamr-linux.cmd
          echo Done running codegen. Errorlevel %errorlevel%
  
          if %errorlevel% neq 0 exit /b %errorlevel%
    
    
          call %GITHUB_WORKSPACE%\isolette-module\aadl\bin\stacksize-fix.cmd
          
          call %GITHUB_WORKSPACE%\isolette-module\hamr\slang\bin\scalajs.cmd
          echo Done scalajs. Errorlevel %errorlevel%
      
          if %errorlevel% neq 0 exit /b %errorlevel%


          call %GITHUB_WORKSPACE%\isolette-module\hamr\c\bin\compile.cmd
          echo Done compiling C code. Errorlevel %errorlevel%

          if %errorlevel% neq 0 exit /b %errorlevel%


          call %GITHUB_WORKSPACE%\isolette-module\aadl\bin\runCI.cmd          
          echo Done running C demo. Errorlevel %errorlevel%

          if %errorlevel% neq 0 exit /b %errorlevel%

      - name: 'Upload JS'
        uses: actions/upload-artifact@v3
        with:
          name: generated-win-site
          path: |
            isolette-module\hamr\slang\index.html
            isolette-module\hamr\slang\js\main.js
          retention-days: 5

